service: authentication

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions: ${file(src/services/authentication/_functions.yml)}
